[pytest]
testpaths = tests
addopts = --alluredir=allure-results
markers =
    smoke: smoke path tests
    critical: critical path tests
    unit: unit tests
    integration: integration tests
    ui: ui tests