CREATE SCHEMA IF NOT EXISTS BL_3NF;

CREATE TABLE IF NOT EXISTS BL_3NF.ce_source  
(source_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source_entity varchar NOT NULL,
 source_system varchar NOT NULL,
 source_desc varchar NOT NULL,
 insert_dt date NOT NULL,
 update_dt date NOT NULL,
 CONSTRAINT unique_source UNIQUE(source_entity,source_system));

--insert default row
INSERT INTO BL_3NF.ce_source (source_id, source_entity,source_system, source_desc, insert_dt, update_dt)
VALUES (-1,'n.a.','n.a.','n.a.','1900-1-1','1900-1-1');
COMMIT;


CREATE TABLE IF NOT EXISTS BL_3NF.ce_payment_method
(payment_method_id int  PRIMARY KEY,
 payment_method_name varchar NOT NULL,
 source_id int NOT NULL,
 source_entity varchar NOT NULL,
 source_system varchar NOT NULL,
 insert_dt date NOT NULL,
 update_dt date NOT NULL,
 CONSTRAINT pm_source_fk FOREIGN KEY (source_id) REFERENCES BL_3NF.ce_source (source_id) );

INSERT INTO BL_3NF.ce_payment_method (payment_method_id,payment_method_name,
source_id,source_entity,source_system,insert_dt,update_dt) VALUES
(-1,'n.a.',-1,'n.a.','n.a.','1900-1-1','1900-1-1');
COMMIT;

CREATE TABLE IF NOT EXISTS BL_3NF.ce_city (
city_id int PRIMARY KEY,
city_name varchar,
source_id int,
source_entity varchar NOT NULL,
source_system varchar NOT NULL,
insert_dt date NOT NULL,
update_dt date NOT NULL,
CONSTRAINT city_source_fk FOREIGN KEY (source_id) REFERENCES BL_3NF.ce_source (source_id) );

INSERT INTO BL_3NF.ce_city (city_id,city_name,source_id,source_entity,source_system,insert_dt,update_dt)
VALUES (                     -1    ,'n.a.'   , -1      , 'n.a.'       , 'n.a.'      ,'1900-1-1','1900-1-1');
COMMIT;


-- i didn't think we need metada to track genders so we have just 2 columns.
CREATE TABLE IF NOT EXISTS BL_3NF.ce_gender (gender_id int PRIMARY KEY, gender_name varchar);
INSERT INTO BL_3NF.ce_gender (gender_id, gender_name) VALUES (-1, 'n.a.');

CREATE TABLE IF NOT EXISTS BL_3NF.ce_customer (
customer_surr_id int PRIMARY KEY,
customer_src_id varchar,
customer_gender_id int,
birthday date,
source_id int,
source_entity varchar NOT NULL,
source_system varchar NOT NULL,
insert_dt date NOT NULL,
update_dt date NOT NULL,
CONSTRAINT customer_source_fk FOREIGN KEY (source_id) REFERENCES BL_3NF.ce_source (source_id),
CONSTRAINT customer_gender_fk FOREIGN KEY (customer_gender_id) REFERENCES BL_3NF.ce_gender (gender_id)
);



INSERT INTO BL_3NF.ce_customer (customer_surr_id,customer_src_id,customer_gender_id,
birthday,source_id,source_entity,source_system,insert_dt,update_dt) VALUES 
(-1,'n.a.',-1,'1900-1-1',-1,'n.a.','n.a.','1900-1-1','1900-1-1');
COMMIT;


CREATE TABLE IF NOT EXISTS BL_3NF.ce_cashier
(cashier_surr_id int NOT NULL,
cashier_src_id varchar NOT NULL,
cashier_gender_id int NOT NULL, 
birthday date NOT NULL, 
source_id int NOT NULL,
source_entity varchar NOT NULL,
source_system varchar NOT NULL,
insert_dt date NOT NULL,
update_dt date NOT NULL,
CONSTRAINT unique_cashier UNIQUE(cashier_surr_id,start_dt)
CONSTRAINT cashier_source_fk FOREIGN KEY (source_id) REFERENCES BL_3NF.ce_source (source_id),
CONSTRAINT cashier_gender_fk FOREIGN KEY (cashier_gender_id) REFERENCES BL_3NF.ce_gender (gender_id));

INSERT INTO BL_3NF.ce_cashier
(cashier_surr_id ,
cashier_src_id ,
cashier_gender_id , 
birthday , 
source_id ,
source_entity  ,
source_system ,
insert_dt ,
update_dt ) VALUES
(-1, 'n.a', -1, '1900-1-1', -1, 'n.a.','n.a.',  '1900-1-1','1900-1-1');
COMMIT;

CREATE TABLE IF NOT EXISTS BL_3NF.ce_store (
store_id int PRIMARY KEY,
store_name varchar,
city_id int,
source_id varchar NOT NULL,
source_entity varchar NOT NULL,
source_system varchar NOT NULL,
update_dt date NOT NULL,
insert_dt date NOT NULL,
CONSTRAINT store_city_fk FOREIGN KEY (city_id) REFERENCES BL_3NF.ce_city (city_id),
CONSTRAINT store_source_fk FOREIGN KEY (source_id) REFERENCES BL_3NF.ce_source (source_id));

INSERT INTO BL_3NF.ce_store (
store_id ,
store_name ,
city_id ,
source_id ,
source_entity,
source_system ,
insert_dt ,
update_dt )
VALUES (-1,'n.a',-1,-1,'n.a','n.a','1900-1-1','1900-1-1');
COMMIT;

CREATE TABLE IF NOT EXISTS BL_3NF.ce_transactions (
transaction_surr_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
transaction_src_id varchar,
store_id int,
transaction_date date,
cashier_surr_id int,
customer_surr_id int,
items_count smallint,
total_amount_ngn decimal,
discount_applied boolean,
loyalty_points_earned int,
payment_method_id smallint,
source_id int,
source_system varchar,
source_entity varchar,
insert_dt date,
update_dt date,
CONSTRAINT transaction_store_fk FOREIGN KEY (store_id) REFERENCES BL_3NF.ce_store (store_id),
CONSTRAINT transacrion_cashier_fk FOREIGN KEY (cashier_surr_id) REFERENCES  BL_3NF.ce_cashier (cashier_surr_id),
CONSTRAINT transaction_payment_method_fk FOREIGN KEY (payment_method_id) REFERENCES  BL_3NF.ce_payment_method (payment_method_id),
CONSTRAINT transaction_source_fk FOREIGN KEY (source_id) REFERENCES BL_3NF.ce_source (source_id),
CONSTRAINT unique_transaction UNIQUE (transaction_src_id,source_id)
);

CREATE TABLE IF NOT EXISTS BL_3NF.ce_store_cashier (
store_id int,
cashier_surr_id int,
source_system varchar,
source_id int,
source_entity varchar,
start_dt date,
end_dt date,
insert_dt date,
is_active boolean,
CONSTRAINT cashier_store_source_fk FOREIGN KEY (source_id) REFERENCES BL_3NF.ce_source (source_id),
CONSTRAINT cashier_store_store_fk FOREIGN KEY (store_id) REFERENCES BL_3NF.ce_store (store_id),
CONSTRAINT cashier_store_cashier_fk FOREIGN KEY (cashier_surr_id) REFERENCES BL_3NF.ce_cashier (cashier_surr_id),
CONSTRAINT cashier_store_comp_key UNIQUE (store_id,cashier_surr_id,start_dt)
);

INSERT INTO BL_3NF.ce_store_cashier (
store_id ,
cashier_surr_id ,
source_system ,
source_id ,
source_entity ,
start_dt ,
end_dt ,
insert_dt ,
is_active 
)

VALUES (-1,-1,'n.a.',-1,'n.a.','1900-1-1','1900-1-1','1900-1-1',TRUE);
COMMIT;

--let's populate the tables now

INSERT INTO BL_3NF.ce_source (
source_entity, source_system,source_desc,insert_dt,update_dt
)
VALUES 
('src_source1','sa_source1','Table for online sales',current_date,current_date),
('src_source2','sa_source2','Table for physical sales',current_date,current_date),
('map_cashier','bl_cl', 'Mapping to remove duplicate cashiers',current_date,current_date),
('map_city','bl_cl', 'Mapping to remove duplicate cities',current_date,current_date),
('map_customer','bl_cl', 'Mapping to remove duplicate customers',current_date,current_date),
('map_payment_method','bl_cl', 'Mapping to remove duplicate payment methods',current_date,current_date),
('map_store','bl_cl', 'Mapping to remove duplicate stores',current_date,current_date),
('ce_transactions','bl_3nf','Normalized table of all sales',current_date,current_date)
ON CONFLICT (source_entity,source_system) DO NOTHING;
COMMIT;

INSERT INTO BL_3NF.ce_payment_method (payment_method_id,payment_method_name,
source_id,source_entity,source_system,insert_dt, update_dt)
SELECT DISTINCT payment_method_id, pm_name,
(SELECT source_id  FROM BL_3NF.ce_source WHERE source_entity = 'map_payment_method'),
'map_payment_method', 'bl_cl', current_date,current_date
FROM bl_cl.map_payment_method
ON CONFLICT (payment_method_id) DO NOTHING;
COMMIT;


INSERT INTO BL_3NF.ce_city
(city_id,city_name,source_id,source_entity,source_system,insert_dt,update_dt) 
SELECT DISTINCT city_id,city_name,
(SELECT source_id FROM BL_3NF.ce_source WHERE source_entity = 'map_city'),
'map_city', 'bl_cl', current_date,current_date
FROM bl_cl.map_city
ON CONFLICT (city_id) DO NOTHING;
COMMIT;

INSERT INTO BL_3NF.ce_gender (gender_id,gender_name)
VALUES (1,'Male'), (2,'Female');
COMMIT;

INSERT INTO BL_3NF.ce_customer (
customer_surr_id,
customer_src_id,
customer_gender_id,
birthday,
source_id,
source_entity,
source_system,
insert_dt,
update_dt
)
SELECT DISTINCT 
customer_surr_id,
customer_src_id,
(SELECT gender_id FROM bl_3nf.ce_gender WHERE UPPER(customer_gender) = UPPER (gender_name)),
customer_birthday,
(SELECT source_id FROM BL_3NF.ce_source WHERE source_entity = 'map_customer'),
'map_customer',
'bl_cl',
current_date,
current_date
FROM bl_cl.map_customer
ON CONFLICT (customer_surr_id) DO NOTHING;
COMMIT;

INSERT INTO BL_3NF.ce_cashier(
cashier_surr_id,
cashier_src_id,
cashier_gender_id,
birthday,
source_id,
source_entity,
source_system,
insert_dt,
update_dt
)
SELECT DISTINCT 
cashier_surr_id,
cashier_src_id,
(SELECT gender_id FROM bl_3nf.ce_gender WHERE UPPER(cashier_gender) = UPPER (gender_name)),
cashier_birthday,
(SELECT source_id FROM BL_3NF.ce_source WHERE source_entity = 'map_cashier'),
'map_cashier',
'bl_cl',
current_date,
current_date
FROM bl_cl.map_cashier
ON CONFLICT (cashier_surr_id) DO NOTHING;
COMMIT;


INSERT INTO BL_3NF.ce_store (
store_id,
store_name,
city_id,
is_active,
source_id,
source_entity,
source_system,
start_dt,
end_dt,
update_dt
)
SELECT DISTINCT
store_id,
store_name,
(SELECT city_id FROM bl_3nf.ce_city WHERE store_city = city_name),
TRUE,
(SELECT source_id FROM BL_3NF.ce_source WHERE source_entity = 'map_store'),
'map_store',
'bl_cl',
current_date,
current_date,
current_date
FROM bl_cl.map_store
ON CONFLICT (store_id) DO NOTHING;
COMMIT;

INSERT INTO BL_3NF.ce_transactions (
    transaction_src_id,
    store_id,
    transaction_date,
    cashier_surr_id,
    customer_surr_id,
    items_count,
    total_amount_ngn,
    discount_applied,
    loyalty_points_earned,
    payment_method_id,
    source_id,
    source_system,
    source_entity,
    insert_dt,
    update_dt
)
SELECT
    src.transaction_id,
    s.store_id,
    src.transaction_date::date,
    c.cashier_surr_id,
    cu.customer_surr_id,
    src.items_count::smallint,
    src.total_amount_ngn::numeric,
    src.discount_applied::boolean,
    src.loyalty_points_earned::int,
    pm.payment_method_id,
    so.source_id,
    'sa_source1',
    'src_source1',
    current_date,
    current_date
FROM sa_source1.src_source1 src
JOIN bl_3nf.ce_store s
    ON s.store_name = src.store_name
JOIN bl_3nf.ce_city ci
    ON ci.city_id = s.city_id
   AND ci.city_name = src.city
JOIN bl_3nf.ce_cashier c
    ON c.cashier_src_id = src.cashier_id
JOIN bl_3nf.ce_customer cu
    ON cu.customer_src_id = src.customer_id
JOIN bl_3nf.ce_payment_method pm
    ON pm.payment_method_name = src.payment_method
JOIN bl_3nf.ce_source so
    ON so.source_entity = 'src_source1'
ON CONFLICT (transaction_src_id, source_id) DO NOTHING;
COMMIT;


INSERT INTO BL_3NF.ce_transactions (
    transaction_src_id,
    store_id,
    transaction_date,
    cashier_surr_id,
    customer_surr_id,
    items_count,
    total_amount_ngn,
    discount_applied,
    loyalty_points_earned,
    payment_method_id,
    source_id,
    source_system,
    source_entity,
    insert_dt,
    update_dt
)
SELECT
    src.transaction_id,
    s.store_id,
    src.transaction_date::date,
    c.cashier_surr_id,
    cu.customer_surr_id,
    src.items_count::smallint,
    src.total_amount_ngn::numeric,
    src.discount_applied::boolean,
    src.loyalty_points_earned::int,
    pm.payment_method_id,
    so.source_id,
    'sa_source2',
    'src_source2',
    current_date,
    current_date
FROM sa_source1.src_source1 src
JOIN bl_3nf.ce_store s
    ON s.store_name = src.store_name
JOIN bl_3nf.ce_city ci
    ON ci.city_id = s.city_id
   AND ci.city_name = src.city
JOIN bl_3nf.ce_cashier c
    ON c.cashier_src_id = src.cashier_id
JOIN bl_3nf.ce_customer cu
    ON cu.customer_src_id = src.customer_id
JOIN bl_3nf.ce_payment_method pm
    ON pm.payment_method_name = src.payment_method
JOIN bl_3nf.ce_source so
    ON so.source_entity = 'src_source2'
ON CONFLICT (transaction_src_id, source_id) DO NOTHING;
COMMIT;

WITH ranking AS (
SELECT cashier_surr_id, store_id, transaction_date,
ROW_NUMBER () OVER (PARTITION BY cashier_surr_id ORDER BY transaction_date desc) as num
FROM bl_3nf.ce_transactions),
last_stores AS (
SELECT * FROM ranking WHERE num =1 )

INSERT INTO bl_3nf.ce_store_cashier (
store_id,
cashier_surr_id,
source_system,
source_id,
source_entity,
start_dt,
end_dt,
insert_dt,
is_active
)
SELECT 
store_id,
cashier_surr_id,
'bl_3nf',
(SELECT source_id FROM bl_3nf.ce_source WHERE source_entity = 'ce_transactions'),
'ce_transactions',
current_date,
'9999-12-31',
current_date,
TRUE
FROM last_stores
ON CONFLICT (store_id,cashier_surr_id,start_dt) DO NOTHING;
COMMIT;

























